---
- hosts: 127.0.0.1
  connection: local
  vars:
    # Installation path in server
    workdir: /root
    url_base_gitlab: https://gitlab.com/cabildo-tf/vente/monitoring/arcgis-backup/-/raw/dev/scripts
    script_filename: generate_properties.sh
    properties_path: "{{ workdir }}/properties"

  tasks:
    - name: Download script for generate properties
      get_url:
        url: "{{ url_base_gitlab }}/{{ script_filename }}"
        dest: "{{ workdir }}/{{ script_filename }}"

    - name: Change permisions
      file: 
        path: "{{ workdir }}/{{ script_filename }}"
        mode: '0777'

    - name: Generate Properties path
      file:
        path: "{{ properties_path }}"
        state: directory

    - name: Generate properties incremental backup
      vars:
        backup_type: incremental
        properties_filename: "webgisdr-{{ backup_type }}.properties"
      command: "{{ workdir }}/{{ script_filename }} -t {{ backup_type }} -f {{ properties_path }}/{{ properties_filename }}"

    - name: Generate properties full backup
      vars:
        backup_type: full
        properties_filename: "webgisdr-{{ backup_type }}.properties"
      command: "{{ workdir }}/{{ script_filename }} -t {{ backup_type }} -f {{ properties_path }}/{{ properties_filename }}"


- hosts: windows
  gather_facts: true
  vars:
    workdir: "{{ lookup('env', 'WORK_DIR') }}"
    pushgateway_credentials_path: "{{ workdir }}/credentials.xml"
    properties_path: /root/properties
    generate_credentials_filename: generate_credentials.ps1
    backup_filename: backup.ps1
    url_base_gitlab: https://gitlab.com/cabildo-tf/vente/monitoring/arcgis-backup/-/raw/dev/scripts
    powershell_path: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
    webgisdr_runnable_path: C:\Program Files\ArcGIS\Portal\tools\webgisdr\webgisdr.bat
    arcgis_datastore_tool_path: C:\Program Files\ArcGIS\DataStore\tools
    arcgis_datastore_changedbproperties_path: "{{ arcgis_datastore_tool_path }}\\changedbproperties.bat"
    pushgateway_host: "{{ lookup('env', 'PUSHGATEWAY_HOST') }}"
    pushgateway_job: "arcgis-backup"
    task_user: "{{ lookup('env', 'TASK_USER') }}"
    task_password: "{{ lookup('env', 'TASK_PASSWORD') }}"
    minio_alias: "{{ lookup('env', 'MINIO_ALIAS') }}"
    minio_bucket: "{{ lookup('env', 'MINIO_BUCKET') }}"
  tasks:
  - name: "Check {{ webgisdr_runnable_path}} exists"
    win_stat:
      path: "{{ webgisdr_runnable_path }}"
    register: webgisdr_status

  - name: Fail if not exists webgisdr
    fail:
      msg: "Not exists {{ webgisdr_runnable_path }}"
    when: webgisdr_status.stat.exists == false

  - name: Create structure directories
    win_file:
      path: "{{ workdir }}/{{ item.path }}"
      state: directory
    loop:
      - { path: "logs" }
      - { path: "tmp/full/temporal" }
      - { path: "tmp/incremental/temporal" }

  - name: Share backup folder
    win_share:
      name: ArcGIS-Backup
      description: ArcGIS backup
      path: "{{ workdir }}/tmp"
      full: "{{ task_user }}"

  - name: Copy properties files to {{ workdir }}
    win_copy:
      src: "{{ properties_path }}/"
      dest: "{{ workdir }}/"

  - name: "Download scripts"
    win_get_url:
      url: "{{ url_base_gitlab }}/{{ item.filename }}"
      dest: "{{ workdir }}/{{ item.filename }}"
      follow_redirects: all
    loop:
      - { filename: "{{ generate_credentials_filename }}" }
      - { filename: "{{ backup_filename }}" }

  - name: "Download minio cli"
    win_get_url:
      url: "https://dl.min.io/client/mc/release/windows-amd64/mc.exe"
      dest: "{{ workdir }}/mc.exe"
      follow_redirects: all

  - name: "Add {{ task_user }} allow rights to folder {{ workdir }}"
    win_acl:
      path: "{{ workdir }}"
      user: "{{ task_user }}"
      rights: FullControl
      type: allow
      state: present
      inherit: ContainerInherit, ObjectInherit
      propagation: 'None'

  - name: "Set minio default"
    vars:
      minio_host: "{{ lookup('env', 'MINIO_HOST') }}"
      minio_user: "{{ lookup('env', 'MINIO_USER') }}"
      minio_pass: "{{ lookup('env', 'MINIO_PASS') }}"
    win_command: "{{ workdir }}/mc.exe alias set {{ minio_alias }} {{ minio_host }} {{ minio_user }} {{ minio_pass }}"
    become: yes
    become_user: "{{ task_user }}"
    become_method: "runas"

  - name: "Generate pushgateway credentials: {{ pushgateway_credentials_path }}"
    vars:
      user: "{{ lookup('env', 'PUSHGATEWAY_USER') }}"
      password: "{{ lookup('env', 'PUSHGATEWAY_PASS') }}"
    win_command: "powershell.exe -ExecutionPolicy ByPass -File {{ workdir }}/{{ generate_credentials_filename }} -user {{ user }} -password {{ password }} -path {{ pushgateway_credentials_path }}"
    become: yes
    become_user: "{{ task_user }}"
    become_method: "runas"

  - name: Create schedule task - ArcGIS Backup full
    vars:
      type: full
      file_properties: "{{ workdir }}/webgisdr-{{ type }}.properties"
      num_keep_backups: 1
    win_scheduled_task:
      name: ArcGIS Enterprise - Full backup
      description: Backup full de ArcGIS Enterprise
      actions:
      - path: '{{ powershell_path }}'
        arguments: >
          -Command "& '{{ workdir }}/{{ backup_filename }}'
          -workdir '{{ workdir }}'
          -pushgateway_host {{ pushgateway_host }}
          -pushgateway_job '{{ pushgateway_job }}-{{ type }}'
          -pushgateway_credential '{{ pushgateway_credentials_path }}'
          -webgisdr_path '{{ webgisdr_runnable_path }}'
          -file_properties '{{ file_properties }}'"
          -type '{{ type }}'
          -num_keep_backups {{ num_keep_backups }}"
      triggers:
        - type: monthlydow
          start_boundary: '2020-01-01T22:00:00'
          run_on_last_week_of_month: yes
          days_of_week: saturday
          months_of_year: january,february,march,april,may,june,july,august,september,october,november,december
      username: "{{ task_user }}"
      password: "{{ task_password }}"
      logon_type: "password"
      enabled: yes

  - name: Create schedule task - ArcGIS Backup incremental
    vars:
      type: incremental
      file_properties: "{{ workdir }}/webgisdr-{{ type }}.properties"
      num_keep_backups: 1
    win_scheduled_task:
      name: ArcGIS Enterprise - Incremental backup
      description: Backup incremental de ArcGIS Enterprise
      actions:
      - path: '{{ powershell_path }}'
        arguments: >
          -Command "& '{{ workdir }}/{{ backup_filename }}'
          -workdir '{{ workdir }}'
          -pushgateway_host {{ pushgateway_host }}
          -pushgateway_job '{{ pushgateway_job }}-{{ type }}'
          -pushgateway_credential '{{ pushgateway_credentials_path }}'
          -webgisdr_path '{{ webgisdr_runnable_path }}'
          -file_properties '{{ file_properties }}'
          -type '{{ type }}'
          -num_keep_backups {{ num_keep_backups }}"
      triggers:
        - type: weekly
          start_boundary: '2020-01-01T22:00:00'
          days_of_week: friday
      username: "{{ task_user }}"
      password: "{{ task_password }}"
      logon_type: "password"
      enabled: yes

  - name: Check ArcGIS Data Store is installed
    win_stat:
      path: "{{ arcgis_datastore_changedbproperties_path }}"
    register: webgisdr_status
    become: yes
    become_user: "{{ task_user }}"
    become_method: "runas"

  - name: Activate point-in time recovery in ArcGIS Data Store
    win_stat:
      path: "{{ arcgis_datastore_changedbproperties_path }} --store relational --pitr enable"
    when: webgisdr_status.stat.exists
    become: yes
    become_user: "{{ task_user }}"
    become_method: "runas"