---
- hosts: 127.0.0.1
  connection: local
  vars:
    # Installation path in server
    workdir: /root
    url_base_gitlab: https://gitlab.com/cabildo-tf/vente/monitoring/arcgis-backup/-/raw/dev/scripts
    script_filename: generate_properties.sh
    properties_path: "{{ workdir }}/properties"

  tasks:
    - name: Download script for generate properties
      get_url:
        url: "{{ url_base_gitlab }}/{{ script_filename }}"
        dest: "{{ workdir }}/{{ script_filename }}"

    - name: Change permisions
      file: 
        path: "{{ workdir }}/{{ script_filename }}"
        mode: '0777'

    - name: Generate Properties path
      file:
        path: "{{ properties_path }}"
        state: directory

    - name: Generate properties incremental backup
      vars:
        backup_type: incremental
        properties_filename: "webgisdr-{{ backup_type }}.properties"
      command: "{{ workdir }}/{{ script_filename }} -t {{ backup_type }} -f {{ properties_path }}/{{ properties_filename }}"

    - name: Generate properties full backup
      vars:
        backup_type: full
        properties_filename: "webgisdr-{{ backup_type }}.properties"
      command: "{{ workdir }}/{{ script_filename }} -t {{ backup_type }} -f {{ properties_path }}/{{ properties_filename }}"


- hosts: windows
  gather_facts: true
  vars:
    workdir: C:\arcgis-backup
    pushgateway_credentials_path: "{{ workdir }}/credentials.xml"
    properties_path: /root/properties
    generate_credentials_filename: generate_credentials.ps1
    backup_filename: backup.ps1
    url_base_gitlab: https://gitlab.com/cabildo-tf/vente/monitoring/arcgis-backup/-/raw/dev/scripts
    powershell_path: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
    webgisdr_runnable_path: C:\Program Files\ArcGIS\Portal\tools\webgisdr\webgisdr.bat
    pushgateway_host: "{{ lookup('env', 'PUSHGATEWAY_HOST') }}"
    pushgateway_job: "arcgis-backup"
    user: "{{ lookup('env', 'TASK_USER') }}"
    password: "{{ lookup('env', 'TASK_PASSWORD') }}"
  tasks: 
  - name: Create directory {{ workdir }}
    win_file:
      path: "{{ workdir }}"
      state: directory

  - name: Copy properties files to {{ workdir }}
    win_copy:
      src: "{{ properties_path }}/"
      dest: "{{ workdir }}/"

  - name: "Download script {{ generate_credentials_filename }}"
    win_get_url:
      url: "{{ url_base_gitlab }}/{{ generate_credentials_filename }}"
      dest: "{{ workdir }}/{{ generate_credentials_filename }}"
      follow_redirects: all

  - name: "Generate pushgateway credentials: {{ pushgateway_credentials_path }}"
    vars:
      user: "{{ lookup('env', 'PUSHGATEWAY_USER') }}"
      password: "{{ lookup('env', 'PUSHGATEWAY_PASS') }}"
    win_command: "powershell.exe -ExecutionPolicy ByPass -File {{ workdir }}/{{ generate_credentials_filename }} -user {{ user }} -password {{ password }} -path {{ pushgateway_credentials_path }}"

  - name: "Download script {{ backup_filename }}"
    vars:
    win_get_url:
      url: "{{ url_base_gitlab }}/{{ backup_filename }}"
      dest: "{{ workdir }}/{{ backup_filename }}"
      follow_redirects: all

  - name: Create schedule task - ArcGIS Backup full
    vars:
      file_properties: "{{ workdir }}/webgisdr-full.properties"
    win_scheduled_task:
      name: ArcGIS Enterprise - Full backup
      description: Backup full de ArcGIS Enterprise
      actions:
      - path: '{{ powershell_path }}'
        arguments: >
          -Command "& '{{ workdir }}/{{ backup_filename }}' 
          -workdir '{{ workdir }}' 
          -pushgateway_host {{ pushgateway_host }} 
          -pushgateway_job {{ pushgateway_job }} 
          -pushgateway_credential '{{ pushgateway_credentials_path }}' 
          -webgisdr_path '{{ webgisdr_runnable_path }}' 
          -file_properties '{{ file_properties }}'"
          -type 'full'"
      triggers:
        - type: weekly
          start_boundary: '2020-01-01T22:00:00'
          run_on_last_week_of_month: yes
          days_of_week: saturday
          months_of_year: january,february,march,april,may,june,july,august,september,october,november,december
      username: "{{ user }}"
      password: "{{ password }}"
      logon_type: "password"
      enabled: yes

  - name: Create schedule task - ArcGIS Backup incremental
    vars:
      file_properties: "{{ workdir }}/webgisdr-incremental.properties"
    win_scheduled_task:
      name: ArcGIS Enterprise - Incremental backup
      description: Backup incremental de ArcGIS Enterprise
      actions:
      - path: '{{ powershell_path }}'
        arguments: >
          -Command "& '{{ workdir }}/{{ backup_filename }}' 
          -workdir '{{ workdir }}' 
          -pushgateway_host {{ pushgateway_host }} 
          -pushgateway_job {{ pushgateway_job }} 
          -pushgateway_credential '{{ pushgateway_credentials_path }}' 
          -webgisdr_path '{{ webgisdr_runnable_path }}' 
          -file_properties '{{ file_properties }}'
          -type 'incremental'"
      triggers:
        - type: monthlydow
          start_boundary: '2020-01-01T22:00:00'
          days_of_week: friday
      username: "{{ user }}"
      password: "{{ password }}"
      logon_type: "password"
      enabled: yes