---
- hosts: 127.0.0.1
  connection: local
  vars:
    # Installation path in server
    workdir: /root
    script_filename: generate_properties.sh
    url: https://gist.githubusercontent.com/nacholore/d3b5281b0dae96be51d499d575fcd835/raw/9853b4d2188c28a9a12b35941b0e2cd40bce0cbf
    properties_path: "{{ workdir }}/properties"

  tasks:
    - name: Download script for generate properties
      get_url:
        url: "{{ url }}/{{ script_filename }}"
        dest: "{{ workdir }}/{{ script_filename }}"

    - name: Change permisions
      file: 
        path: "{{ workdir }}/{{ script_filename }}"
        mode: '0777'

    - name: Generate Properties path
      file:
        path: "{{ properties_path }}"
        state: directory

    - name: Generate properties incremental backup
      vars:
        backup_type: incremental
        properties_filename: "webgisdr-{{ backup_type }}.properties"
      command: "{{ workdir }}/{{ script_filename }} -t {{ backup_type }} -f {{ properties_path }}/{{ properties_filename }}"

    - name: Generate properties full backup
      vars:
        backup_type: full
        properties_filename: "webgisdr-{{ backup_type }}.properties"
      command: "{{ workdir }}/{{ script_filename }} -t {{ backup_type }} -f {{ properties_path }}/{{ properties_filename }}"


- hosts: windows
  gather_facts: true
  vars:
    workdir: C:\arcgis-backup
    pushgateway_credentials_path: "{{ workdir }}/credentials.xml"
    properties_path: /root/properties
    filename_generate_credentials: generate-credentials.ps1
  tasks: 
  - name: Create directory {{ workdir }}
    win_file:
      path: "{{ workdir }}"
      state: directory

  - name: Copy properties files to {{ workdir }}
    win_copy:
      src: "{{ properties_path }}/"
      dest: "{{ workdir }}/"

  - name: Download script generate credentials
    vars:
      url_base: https://gist.githubusercontent.com/nacholore/0dba5c5f2dbbf3c2c5fbb993720233d1/raw/b350ca116f4e5091f05b0f9a52f62350f6b30d41/
    win_get_url:
      url: "{{ url_base }}/{{ filename_generate_credentials }}"
      dest: "{{ workdir }}/{{ filename_generate_credentials }}"
      follow_redirects: all

  - name: Generate credentials
    vars:
      user: "{{ lookup('env', 'PUSHGATEWAY_USER') }}"
      password: "{{ lookup('env', 'PUSHGATEWAY_PASS') }}"
    win_command: "powershell.exe -ExecutionPolicy ByPass -File {{ workdir }}/{{ filename_generate_credentials }} -user {{ user }} -password {{ password }} -path {{ pushgateway_credentials_path }}"

  - name: Create schedule task - ArcGIS Backup incremental
    vars:
      pushgateway_host: "{{ lookup('env', 'PUSHGATEWAY_HOST') }}"
      pushgateway_job: "arcgis-backup"
      webgisdr_runnable_path: C:\Program Files\ArcGIS\Portal\tools\webgisdr\webgisdr.bat
      file_properties: "{{ workdir }}/webgisdr-incremental.properties"
      user: "{{ lookup('env', 'TASK_USER') }}"
      password: "{{ lookup('env', 'TASK_PASSWORD') }}"
    win_scheduled_task:
      name: ArcGIS - Incremental backup
      description: Backup incremental de ArcGIS Enterprise
      actions:
      - path: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
        arguments: >
          "-ExecutionPolicy Unrestricted 
          -NonInteractive 
          -File C:\arcgis-backup\backup.ps1 -workdir {{ workdir }} 
          -pushgateway_host {{ pushgateway_host }}
          -pushgateway_job {{ pushgateway_job }}
          -pushgateway_credential '{{ pushgateway_credentials_path }}'
          -webgisdr_path '{{ webgisdr_runnable_path }}'
          -file_properties '{{ file_properties }}'"
      triggers:
        - type: monthlydow
          start_boundary: '2020-01-01T22:00:00'
          run_on_last_week_of_month: yes
          days_of_week: saturday
          months_of_year: january,february,march,april,may,june,july,august,september,october,november,december
      username: "{{ user }}"
      password: "{{ password }}"
      logon_type: "password"
      enabled: yes

  - name: Create schedule task - ArcGIS Backup full
    vars:
      pushgateway_host: "{{ lookup('env', 'PUSHGATEWAY_HOST') }}"
      pushgateway_job: "arcgis-backup"
      webgisdr_runnable_path: C:\Program Files\ArcGIS\Portal\tools\webgisdr\webgisdr.bat
      file_properties: "{{ workdir }}/webgisdr-full.properties"
      user: "{{ lookup('env', 'TASK_USER') }}"
      password: "{{ lookup('env', 'TASK_PASSWORD') }}"
    win_scheduled_task:
      name: ArcGIS - Full backup
      description: Backup full de ArcGIS Enterprise
      actions:
      - path: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
        arguments: >
          "-ExecutionPolicy Unrestricted 
          -NonInteractive 
          -File C:\arcgis-backup\backup.ps1 -workdir '{{ workdir }}' 
          -pushgateway_host {{ pushgateway_host }}
          -pushgateway_job {{ pushgateway_job }}
          -pushgateway_credential '{{ pushgateway_credentials_path }}'
          -webgisdr_path '{{ webgisdr_runnable_path }}'
          -file_properties '{{ file_properties }}'"
      triggers:
        - type: monthlydow
          start_boundary: '2020-01-01T22:00:00'
          run_on_last_week_of_month: yes
          days_of_week: saturday
          months_of_year: january,february,march,april,may,june,july,august,september,october,november,december
      username: "{{ user }}"
      password: "{{ password }}"
      logon_type: "password"
